/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.Produto;
import model.beans.Venda_produto;
import model.dao.ProdutoDAO;

/**
 *
 * @author Gustavo Lobo
 */
public class AdicionarProduto_GerarVenda extends javax.swing.JFrame {

    private GerarVenda tela_GerarVenda;

    /**
     * Creates new form ConsultaProduto
     */
    public AdicionarProduto_GerarVenda() {
        initComponents();
    }

    public void linkar(GerarVenda tela_GerarVenda) {
        this.tela_GerarVenda = tela_GerarVenda;
    }

    public void limparTodosCampos() {
        lbltxt_ProdutoCodigo.setText("");
        lbltxt_ProdutoNome.setText("");
        lbltxt_ProdutoPreco.setText("");
        lbltxt_ProdutoCategoria.setText("");
        lbltxt_ProdutoQuantidade.setText("");
        txt_VendaProduto_qtd.setText("");
    }

    public void preencher_PD(String sql) {
        ProdutoDAO dao = new ProdutoDAO();

        List<Produto> consulta_produto = dao.consutar_PD(sql);

        DefaultTableModel tabela = (DefaultTableModel) tb_produtos.getModel();
        tabela.setNumRows(0);

        consulta_produto.forEach((instancia)
                -> {
            tabela.addRow(new Object[]{
                instancia.getNome(),
                instancia.getCategoria(),
                instancia.getPreco()
            });
        });
    }

    public void pesquisaDinamica() {
        String sql = "SELECT * FROM Produto WHERE "
                + "nome LIKE '%" + txt_PesquisaProdutoNome.getText() + "%'";

        this.preencher_PD(sql);
    }

    public void preencherConsulta(String sql) {
        ProdutoDAO dao = new ProdutoDAO();

        Produto consulta_produto = dao.consultar(sql);

        lbltxt_ProdutoCodigo.setText("" + consulta_produto.getCod_prod());
        lbltxt_ProdutoNome.setText(consulta_produto.getNome());
        lbltxt_ProdutoPreco.setText("" + consulta_produto.getPreco());
        lbltxt_ProdutoCategoria.setText(consulta_produto.getCategoria());
        lbltxt_ProdutoQuantidade.setText("" + consulta_produto.getQuantidade());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_ProdutoNome = new javax.swing.JLabel();
        lbl_ProdutoPreco = new javax.swing.JLabel();
        lbl_ProdutoCategoria = new javax.swing.JLabel();
        lbl_ProdutoQuantidade = new javax.swing.JLabel();
        lbl_ProdutoCodigo = new javax.swing.JLabel();
        lbltxt_ProdutoCodigo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_PesquisaNome = new javax.swing.JLabel();
        txt_PesquisaProdutoNome = new javax.swing.JTextField();
        btn_adicionar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_produtos = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_qtd_venda = new javax.swing.JLabel();
        txt_VendaProduto_qtd = new javax.swing.JTextField();
        lbltxt_ProdutoNome = new javax.swing.JLabel();
        lbltxt_ProdutoPreco = new javax.swing.JLabel();
        lbltxt_ProdutoCategoria = new javax.swing.JLabel();
        lbltxt_ProdutoQuantidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADICIONA PRODUTO (GERAR VENDA)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbl_ProdutoNome.setText("Nome");

        lbl_ProdutoPreco.setText("Preço");

        lbl_ProdutoCategoria.setText("Categoria");

        lbl_ProdutoQuantidade.setText("Quantidade");

        lbl_ProdutoCodigo.setText("Código");

        lbltxt_ProdutoCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_PesquisaNome.setText("Pesquisar Nome");

        txt_PesquisaProdutoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PesquisaProdutoNomeKeyReleased(evt);
            }
        });

        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        tb_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Categoria", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_produtos.getTableHeader().setReorderingAllowed(false);
        tb_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_produtos);

        lbl_qtd_venda.setText("Informe a quantidade do produto para vender");

        lbltxt_ProdutoNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltxt_ProdutoPreco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltxt_ProdutoCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltxt_ProdutoQuantidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_PesquisaNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_PesquisaProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(440, 440, 440)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ProdutoNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ProdutoPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ProdutoCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ProdutoQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ProdutoCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltxt_ProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxt_ProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxt_ProdutoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxt_ProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltxt_ProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(459, 459, 459)
                                .addComponent(lbl_qtd_venda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_VendaProduto_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_adicionar)
                                .addGap(75, 75, 75)
                                .addComponent(btn_limpar)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_adicionar, btn_limpar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PesquisaNome)
                    .addComponent(txt_PesquisaProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltxt_ProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ProdutoCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ProdutoNome)
                            .addComponent(lbltxt_ProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ProdutoPreco)
                            .addComponent(lbltxt_ProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ProdutoCategoria)
                            .addComponent(lbltxt_ProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ProdutoQuantidade)
                            .addComponent(lbltxt_ProdutoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_qtd_venda)
                            .addComponent(txt_VendaProduto_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_adicionar)
                            .addComponent(btn_limpar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_adicionar, btn_limpar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.pesquisaDinamica();
    }//GEN-LAST:event_formWindowOpened

    private void txt_PesquisaProdutoNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PesquisaProdutoNomeKeyReleased
        this.pesquisaDinamica();
    }//GEN-LAST:event_txt_PesquisaProdutoNomeKeyReleased

    private void tb_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtosMouseClicked

        int linha = tb_produtos.getSelectedRow();

        String sql = "SELECT * FROM Produto WHERE "
                + "nome = '" + tb_produtos.getValueAt(linha, 0) + "' AND "
                + "categoria = '" + tb_produtos.getValueAt(linha, 1) + "' AND "
                + "preco = " + tb_produtos.getValueAt(linha, 2);

        this.preencherConsulta(sql);
    }//GEN-LAST:event_tb_produtosMouseClicked

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed

        this.limparTodosCampos();
        this.pesquisaDinamica();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed

        if (lbltxt_ProdutoCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o produto que deseja adicionar na venda",
                    "Adicionar Produto", JOptionPane.ERROR_MESSAGE);
        } else if (txt_VendaProduto_qtd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a quantidade do produto que deseja adicionar na venda",
                    "Adicionar Produto", JOptionPane.ERROR_MESSAGE);
        } else {
            int qtd_venda = Integer.parseInt(txt_VendaProduto_qtd.getText());
            int qtd_estoque = Integer.parseInt(lbltxt_ProdutoQuantidade.getText());

            if (qtd_venda <= qtd_estoque) {
                Produto produto = new Produto();

                produto.setCod_prod(Integer.parseInt(lbltxt_ProdutoCodigo.getText()));
                produto.setNome(lbltxt_ProdutoNome.getText());
                produto.setPreco(Double.parseDouble(lbltxt_ProdutoPreco.getText()));
                produto.setQuantidade(Integer.parseInt(lbltxt_ProdutoQuantidade.getText()));

                Venda_produto venda_produto = new Venda_produto();

                venda_produto.setProduto(produto);
                venda_produto.setQtd_prod_venda(Integer.parseInt(txt_VendaProduto_qtd.getText()));

                if (tela_GerarVenda != null) {
                    if (tela_GerarVenda.isInListaProduto(venda_produto) == true) {
                        JOptionPane.showMessageDialog(this, "Produto já está adicionado na venda",
                                "Adicionar Produto", JOptionPane.ERROR_MESSAGE);
                    } else {
                        tela_GerarVenda.importarProduto(venda_produto);
                        this.limparTodosCampos();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Quantidade indisponível no estoque",
                        "Adicionar Produto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_adicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto_GerarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto_GerarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto_GerarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto_GerarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdicionarProduto_GerarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_PesquisaNome;
    private javax.swing.JLabel lbl_ProdutoCategoria;
    private javax.swing.JLabel lbl_ProdutoCodigo;
    private javax.swing.JLabel lbl_ProdutoNome;
    private javax.swing.JLabel lbl_ProdutoPreco;
    private javax.swing.JLabel lbl_ProdutoQuantidade;
    private javax.swing.JLabel lbl_qtd_venda;
    private javax.swing.JLabel lbltxt_ProdutoCategoria;
    private javax.swing.JLabel lbltxt_ProdutoCodigo;
    private javax.swing.JLabel lbltxt_ProdutoNome;
    private javax.swing.JLabel lbltxt_ProdutoPreco;
    private javax.swing.JLabel lbltxt_ProdutoQuantidade;
    private javax.swing.JTable tb_produtos;
    private javax.swing.JTextField txt_PesquisaProdutoNome;
    private javax.swing.JTextField txt_VendaProduto_qtd;
    // End of variables declaration//GEN-END:variables
}
