/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.beans.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author Gustavo Lobo
 */
public class CadastrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastrarCliente() {
        initComponents();
    }

    public void limparTodosCampos() {
        txt_nome.setText("");
        txt_rg.setText("");
        txt_cpf.setText("");
        txt_endereco.setText("");
        txt_n_endereco.setText("");
        txt_cidade.setText("");
        txt_estado.setText("");
        txt_telefone.setText("");
        txt_cel.setText("");
        txt_email.setText("");
    }

    public boolean validacaoCampoVazio() {
        boolean valida = false;

        if (txt_nome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_rg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o RG do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_cpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o CPF do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_endereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o endereco do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_n_endereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o número do endereço do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_cidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a cidade do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_estado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o estado do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            valida = true;
        }

        return valida;
    }

    public boolean validacaoCampoTamanho() {
        boolean valida = false;

        if (txt_nome.getText().length() > 100) {
            JOptionPane.showMessageDialog(this, "Campo nome, tamanho máximo: 100 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_rg.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Campo RG, tamanho máximo: 20 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_cpf.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Campo CPF, tamanho máximo: 20 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_endereco.getText().length() > 100) {
            JOptionPane.showMessageDialog(this, "Campo endereço, tamanho máximo: 100 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_n_endereco.getText().length() > 4) {
            JOptionPane.showMessageDialog(this, "Campo número do endereço, tamanho máximo: 4 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_cidade.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "Campo cidade, tamanho máximo: 50 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_estado.getText().length() > 2) {
            JOptionPane.showMessageDialog(this, "Campo estado, tamanho máximo: 2 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_telefone.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Campo telefone, tamanho máximo: 20 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_cel.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "Campo celular, tamanho máximo: 20 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txt_email.getText().length() > 100) {
            JOptionPane.showMessageDialog(this, "Campo e-mail, tamanho máximo: 100 caracteres",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            valida = true;
        }

        return valida;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Rg = new javax.swing.JLabel();
        lbl_Cpf = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        lbl_Numero = new javax.swing.JLabel();
        lbl_Cidade = new javax.swing.JLabel();
        lbl_Uf = new javax.swing.JLabel();
        lbl_Telefone = new javax.swing.JLabel();
        lbl_Celular = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        txt_rg = new javax.swing.JTextField();
        txt_n_endereco = new javax.swing.JTextField();
        txt_cidade = new javax.swing.JTextField();
        txt_estado = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txt_cel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO DE CLIENTE", 2, 0, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbl_Nome.setText("Nome");

        lbl_Rg.setText("RG");

        lbl_Cpf.setText("CPF");

        lbl_Endereco.setText("Endereço");

        lbl_Numero.setText("Número");

        lbl_Cidade.setText("Cidade");

        lbl_Uf.setText("Estado");

        lbl_Telefone.setText("Telefone");

        lbl_Celular.setText("Celular");

        lbl_Email.setText("E-mail");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Cpf)
                    .addComponent(lbl_Endereco)
                    .addComponent(lbl_Rg)
                    .addComponent(lbl_Numero)
                    .addComponent(lbl_Nome)
                    .addComponent(lbl_Cidade)
                    .addComponent(lbl_Uf)
                    .addComponent(lbl_Telefone)
                    .addComponent(lbl_Celular)
                    .addComponent(lbl_Email))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_endereco)
                    .addComponent(txt_cpf)
                    .addComponent(txt_nome)
                    .addComponent(txt_rg)
                    .addComponent(txt_n_endereco)
                    .addComponent(txt_cidade)
                    .addComponent(txt_estado)
                    .addComponent(txt_telefone)
                    .addComponent(txt_cel)
                    .addComponent(txt_email)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_cadastrar)
                        .addGap(51, 51, 51)
                        .addComponent(btn_limpar)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cadastrar, btn_limpar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Rg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cpf)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Endereco)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Numero)
                    .addComponent(txt_n_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cidade)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Uf)
                    .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Telefone)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Celular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_limpar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_cadastrar, btn_limpar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        
        this.limparTodosCampos();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        
        if (validacaoCampoVazio()) {
            if (validacaoCampoTamanho()) {
                Cliente cliente = new Cliente();

                cliente.setNome(txt_nome.getText());
                cliente.setRg(txt_rg.getText());
                cliente.setCpf(txt_cpf.getText());
                cliente.setEndereco(txt_endereco.getText());
                cliente.setNum_endereco(Integer.parseInt(txt_n_endereco.getText()));
                cliente.setCidade(txt_cidade.getText());
                cliente.setUf(txt_estado.getText());
                cliente.setTelefone(txt_telefone.getText());
                cliente.setCelular(txt_cel.getText());
                cliente.setEmail(txt_email.getText());

                ClienteDAO dao = new ClienteDAO();

                boolean result = dao.cadastrar(cliente);

                if (result == true) {
                    limparTodosCampos();
                    JOptionPane.showMessageDialog(this, "Cliente inserido", "Cliente inserido", JOptionPane.PLAIN_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente não inserido", "Erro", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Celular;
    private javax.swing.JLabel lbl_Cidade;
    private javax.swing.JLabel lbl_Cpf;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Numero;
    private javax.swing.JLabel lbl_Rg;
    private javax.swing.JLabel lbl_Telefone;
    private javax.swing.JLabel lbl_Uf;
    private javax.swing.JTextField txt_cel;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_n_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
